### ISSUE TITLE
Add description of what each ANZSCO does? 

### ISSUE THREAD

**Issue by daviddiviny** [runapp-aus/strayr#45]
This is from the [Australian Skills Classification](https://www.nationalskillscommission.gov.au/australian-skills-classification-resources) . 

![image](https://user-images.githubusercontent.com/6833387/120411421-1df56980-c398-11eb-933e-ae37a01a773f.png)

Is this part of the official definition of each ANSZCO occupation?

**Comment by wfmackey** [comment]
It is! eg: https://www.abs.gov.au/ausstats/abs@.nsf/Previousproducts/086CD5B0C140E5A2CA257B95001310B8?opendocument

Nice of the National Skills Commission to neatly collate it. 

Do you think this should be added to `strayr::anzsco`? If so, because the ASC isn't an exhaustive list of all ANZSCO codes at all levels, we'll need to collect an exhaustive list ourselves. 

Otherwise we can just import the ASC and store it in `strayr::australian_skills_classification` or something.
